- name: psycopg2
  sudo: yes
  apt: name=python-psycopg2 update_cache=true state=present

- name: postgres
  sudo: yes
  apt: name=postgresql-9.3 update_cache=true state=present

- name: postgres vagrant user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name=vagrant role_attr_flags=SUPERUSER state=present
  
- name: postgres vagrant default database
  sudo: yes
  sudo_user: postgres
  postgresql_db: 
    name=vagrant
    encoding="UTF-8"
    lc_collate="en_US.UTF-8"
    lc_ctype="en_US.UTF-8"
    template="template0"
    owner="vagrant"
    state=present