---
- hosts: all
  tasks:
    - include: tasks/essentials.yml
    - include: tasks/postgres.yml
    - include: tasks/dot_files.yml
    - include: tasks/rvm-ruby.yml
    - include: tasks/nvm-node.yml
    - include: tasks/emacs24.yml
